### ISSUE TITLE
Add icon to manifest

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-file-downloader#15]
Currently it shows up with the default icon and seems unfinished when I see it in the extension list 😉

**Comment by daniv-msft** [comment]
Thanks @nschonni for creating this issue.
As this extension is not intended for direct downloading by users (only downloaded as a dependency to another extension), adding an icon for it isn't at the top of our backlog.
I'm keeping this issue opened so that we can prioritize this when we have free cycles.
Thanks!

**Comment by ross-p-smith** [comment]
@nschonni - I'm going to close this as it won't get fixed up
